# Generated by Django 5.1.6 on 2025-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='instalment',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
