# Generated by Django 5.1.6 on 2025-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loan_instalment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='instalment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
